### ISSUE TITLE
Issue with `service:init` command

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#128]
When running the `service:init` command the service cannot start either in dev or deployment because the `package-lock.json` is not generated and the docker image reject it.

2 solutions:
- Execute the `npm i` after create the service (like that we have the latest version)
- Add the package-lock in the template (need to update it for each versions)

**Comment by NicolasMahe** [comment]
outdated issue, command init has been deleted in https://github.com/liteflow-labs/liteflow-js/pull/261
