### ISSUE TITLE
view on IPFS link

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#14]
I think it's weird to open the image when clicking on the "view on IPFS" button on the detail page.

The following NFT has a video and an image, the "view on IPFS" open the image:
https://onlyshoot-bsc-testnet-qmmygb7lt-liteflow.vercel.app/tokens/97-0x92272254a4d7f7dd4cef9cba62ff799b4e8e00bb-25264634205049691864799461239504802752026266192720786694350950215017539647313

I recommend to open the metadata file directly. It the web3 way and people can check the image or video using the metadata file. I think that's what other marketplace are also doing.

@EmmanuelDrouin what do you think?

**Comment by antho1404** [comment]
From my experience, it is the image or nothing, metadata is just for geeks, haha. Having the image instead of the video is weird indeed, maybe we need to display both (or none of them)

**Comment by EmmanuelDrouin** [comment]
I would go with giving both options to the users, view the metadata and view the file.

This is something missing right now on our solution, giving access to the metadata, that most platforms give access to.

**Comment by NicolasMahe** [comment]
closing in favour of https://github.com/liteflow-labs/marketplace-template/issues/78
