### ISSUE TITLE
stream of execution doesn't work in command dev

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#144]
**sometimes**, the stream of execution of the command dev doesn't work. I can only see the orchestrator logs, but not the executions:

<img width="688" alt="Screen Shot 2020-06-10 at 15 05 07" src="https://user-images.githubusercontent.com/5823445/84242987-c711d700-ab2b-11ea-99b3-bcd1b8174fee.png">

It seems to occur 30% to 50% of the time I execute the command dev, and sometimes the first execution is displayed, but not the others.

**Comment by antho1404** [comment]
this should be fixed with the new version
