### ISSUE TITLE
hook `useCreateNFT` should poll both ownership and asset

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#151]
Since the mint of NFT are synced from the blockchain, the hook `useCreateNFT` should also poll the API to check if the NFT has 
been actually synced by the API.
Currently, the hook only check if the ownership is created. As ownership and NFT are independent in the API, if the ownership is created it doesn't mean the NFT has also been created.
In most cases the NFT sync is done right after the Ownership is created, but if for some reason, it take longer, the user will be redirected to a 404 page because the NFT is not yet created.

**Comment by antho1404** [comment]
Actually, the good thing would be to even fetch the asset with the `ownershipExists` instead of the ownership directly

**Comment by NicolasMahe** [comment]
@antho1404 @EmmanuelDrouin can we prioritize this issue? I get a 404 error every time I'm minting a non-lazy mint asset. The fix should be pretty simple.
