### ISSUE TITLE
Compiler service cache is never updated

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#179]
The compiler service cache is never updated.
If the git of a service used by a process using its github URL, then the local cache service is never updated.

We could
- delete the cache at each compilation
- OR improve the cache system to detect update (git commit hash changed, tarball hash is not the same?, etc..) but it will be more complicated and prone to lots of side effect and the cache will not be up to date.

@antho1404 what do you think? what do you recommend?

**Comment by antho1404** [comment]
Got the issue as well.
As a workaround, we can manually delete the cache
```
rm -rf ~/.liteflow-cache
```

Deleting the cache for each compilation makes the cache useless (might be a good quick fix, for now, to simply disable the cache)

Fetching based on the latest commit and caching based on that would be the solution so we could
- Get the last commit hash
- Check if we have this in cache
- If not, download the sources at this commit
- Save in cache with the information of the commit

For the tarball, this is never documented and I think we could/should drop the support of that for now

**Comment by NicolasMahe** [comment]
> For the tarball, this is never documented and I think we could/should drop the support of that for now

I agree
