### ISSUE TITLE
Save state of deployment in the CLI

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#2]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/190
Originally created by @antho1404 on *Tue, 17 Mar 2020 10:19:12 GMT*

---
With https://github.com/mesg-foundation/js-sdk/pull/188 we now automatically deploy services and processes.

It could be nice to have a file that aggregates all the services/runners/processes added on the local network in order to easily debug if needed and create a kind of snapshot of the local chain

**Comment by NicolasMahe** [comment]
seems outdated
