### ISSUE TITLE
Better error when docker is not present

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#232]
When using the `liteflow dev` command, if docker/docker-compose is not installed we have the following error that could be more explicit with something like "please make sure to have docker installed and running"

![image](https://user-images.githubusercontent.com/1783126/91551396-47d6b700-e954-11ea-81a9-1700a0e6344f.png)

**Comment by NicolasMahe** [comment]
closing in favor of https://github.com/liteflow-labs/liteflow-js/issues/233

**Comment by NicolasMahe** [comment]
outdated issue, command dev has been deleted in https://github.com/liteflow-labs/liteflow-js/pull/260
