### ISSUE TITLE
`ENOENT: no such file or directory` when running dev command 

### ISSUE THREAD

**Issue by ninonagy** [liteflow-labs/liteflow-js#233]
This error appears when running `liteflow dev` command on Windows. 

![error](https://user-images.githubusercontent.com/41818057/91559900-2c11e780-e939-11ea-8159-3a4b36be0f90.png)

**Comment by NicolasMahe** [comment]
Thank you for reporting the error. We will fix it shortly.

**Comment by NicolasMahe** [comment]
@ninonagy This issue has been resolve with the latest version of the CLI. Please update liteflow cli to v2.5.0:
```
npm install -g @liteflow/cli@2.5.0
```
