### ISSUE TITLE
Improve state of returned values from Session context

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#30]
Related the following conversation: https://github.com/liteflow-labs/nft/pull/2093#discussion_r982693423

Currently we have the following behavior:
- `ready` is true as soon as the wallet is connected (maybe truthy if the session tried to connect the wallet, but wallet was not previously connected, doesn't wait the user to be logged in
- same issue with `signer`, truthy as soon as the wallet is connected, doesn't wait user to be logged in
- `account`: truthy as soon as the user is fully logged in: wallet connected + authenticated against the API

We should tried to simplify the behaviour of `signer` and maybe `ready` to only returned a value after the user is fully logged in.

Need to be careful with side-effect of this change of behaviour!!!

**Comment by antho1404** [comment]
Closing as the session has been removed
