### ISSUE TITLE
Command help is confusing about usage

### ISSUE THREAD

**Issue by blackinno** [liteflow-labs/liteflow-js#44]
It's confusing about which command should use at liteflow-js, It's `liteflow [command]` or `mesg-cli [command]` if type the command `liteflow --help`

<img width="575" alt="Screen Shot 2563-04-21 at 12 04 35" src="https://user-images.githubusercontent.com/16553272/79827706-3b9c8500-83c9-11ea-9bbe-21e82b438791.png">

**Comment by NicolasMahe** [comment]
other modif:
- [ ] remove docker socket '/var/run/docker.sock'
- [ ] change name in copyright
- [ ] rename label and env prefix to liteflow
- [ ] change address prefix from `mesgtest` to `mesg`

**Comment by antho1404** [comment]
A new version has been released with the fix on the `help`.
Solved by `npm i -g @liteflow/cli@beta`
