### ISSUE TITLE
Flatten deps

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#55]
We currently have Chakra installed multiple time:
```
apps/admin/node_modules/@chakra-ui/react
apps/test/node_modules/@chakra-ui/react
packages/components/node_modules/@chakra-ui/react
packages/templates/node_modules/@chakra-ui/react
```

We should have only have one installation of chakra, any major libs actually, and make sure in the future that deps are flatten to avoid having different versions.

This is the source of issue https://github.com/liteflow-labs/libraries/issues/21.

I created a draft PR to test and it's working well:
https://github.com/liteflow-labs/nft/pull/1988
Need to redo the PR properly without removing all the extra deps to make it work.

**Comment by achampagnedev** [comment]
@NicolasMahe Do you think these 2 could be related? https://github.com/liteflow-labs/nft/pull/2219. It works fine in `@nft/components` but have issue to build in `@nft/templates` There's a ChakraUI in each package.

**Comment by NicolasMahe** [comment]
> @NicolasMahe Do you think these 2 could be related? liteflow-labs/nft#2219. It works fine in `@nft/components` but have issue to build in `@nft/templates` There's a ChakraUI in each package.

I have no idea. Seems more like an issue with a webpack config. Make sure the version of chakra and all storybook deps are the same between templates and components

**Comment by achampagnedev** [comment]
> > @NicolasMahe Do you think these 2 could be related? liteflow-labs/nft#2219. It works fine in `@nft/components` but have issue to build in `@nft/templates` There's a ChakraUI in each package.
> 
> I have no idea. Seems more like an issue with a webpack config. Make sure the version of chakra and all storybook deps are the same between templates and components

Ok yes, I already checked and they are the same that's why I asked, I can see it mention Webpack, just wondering why templates would trigger a webpack error with all the same packages related to chakra and storybook with same versions. Thanks
