### ISSUE TITLE
Make reading of element in array typesafe

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#6]
A lot of place in the codebase use `array[index]` (eg: `.nodes[0]`) to access the first node.
Most of them have a check on `nodes` to make sure it has at least one element or fallback to undefined.
This is good and this should be applied everywhere.

Another code improvement that could be done is to NOT use `array[index]` anymore.
The problem is `array[index]` type is only `X` but not `X | undefined`.
One solution is the `array.at(index)` function that return `X | undefined` type. This will make it type safe but it doesn't work with conditional operator.

**Comment by NicolasMahe** [comment]
@achampagnedev I let you prioritise this improvement please

**Comment by EmmanuelDrouin** [comment]
Idea is tracked here https://trello.com/c/sKMvpjPr/77-reading-of-element-in-array-typesafe closing this issue as the discussion needs to move to Trello

**Comment by NicolasMahe** [comment]
@EmmanuelDrouin  I'm not sure this has value to be on Trello. This is purely code improvement. This could actually be set a a bug and fixed really quickly.

**Comment by EmmanuelDrouin** [comment]
> @EmmanuelDrouin I'm not sure this has value to be on Trello. This is purely code improvement. This could actually be set a a bug and fixed really quickly.

All good with that, I'm gonna add a bug label on this issue and remove it from Trello ;)

**Comment by NicolasMahe** [comment]
Should activate ts compiler option `noUncheckedIndexedAccess`

https://www.reddit.com/r/typescript/comments/winv9g/why_does_accessing_an_element_in_an_array_with/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Also check other cool option from ts: https://www.typescriptlang.org/tsconfig#Type_Checking_6248
