### ISSUE TITLE
Out of gas in location

### ISSUE THREAD

**Issue by blackinno** [liteflow-labs/liteflow-js#61]
<img width="832" alt="Screen Shot 2563-04-24 at 18 28 49" src="https://user-images.githubusercontent.com/16553272/80208132-c09dcd80-8659-11ea-96bb-279e033b769c.png">

**Comment by NicolasMahe** [comment]
@blackinno I did a nice fix in https://github.com/liteflow-labs/liteflow-js/pull/62. please try and tell me if it working.
