### ISSUE TITLE
Fix tests on macOS

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#63]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/227
Originally created by @antho1404 on *Fri, 10 Apr 2020 08:19:46 GMT*

---
New integration tests were added in the PR https://github.com/mesg-foundation/js-sdk/pull/224 but it results in never-ending tests on mac environment on the CI while everything is working correctly on local

**Comment by NicolasMahe** [comment]
outdated
