### ISSUE TITLE
Move dependencies as peerDependencies

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#69]
Some dependencies are directly added within the packages but should not as this makes it complicated to have all the versions correct between the app and the libraries.
Instead, we should use the `peerDependencies` and make sure that the applications are responsible for installing the dependencies.

List of dependencies that could be moved as peer:

- React (we could even have a `^17.0.2 || ^18.0.0`)
- All the chakra packages that we import (we could probably remove the emotion and framer packages as we don't use them directly, also might be compatible with 1.8.8 and 2.x maybe)
- next

**Comment by NicolasMahe** [comment]
I see PR https://github.com/liteflow-labs/liteflow-js/pull/97 did the React part. As Chakra and Next are not part of the packages anymore, I think this issue is good to close.
