### ISSUE TITLE
Single environment and merge process and service dev into dev command

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#70]
- [x] Remove PID feature (https://github.com/liteflow-labs/liteflow-js/pull/72)
- [x] Remove engine data binding to local folder (keep config binding) (https://github.com/liteflow-labs/liteflow-js/pull/72)
- [x] limit env to only one: throw error if it an existing env is running. the first instance of dev should not be stopped. (https://github.com/liteflow-labs/liteflow-js/pull/83)
- [x] Add `service:logs` and `process:logs` commands (or one `logs` command that use flag) OR show all logs directly in the command dev using different color, etc... (https://github.com/liteflow-labs/liteflow-js/pull/75)
- [ ] Merge `process:dev` and `service:dev` into `dev` by adding flags to dev only one process or one service
- [x] Add a flag to the `dev` command to force deleting existing env. show it when an existing env exists (#83)

optional:
- [x] add a `.liteflowrc` in the project folder to keep configs (https://github.com/liteflow-labs/liteflow-js/pull/72)

@antho1404 please update this issue or give your feedback

**Comment by NicolasMahe** [comment]
> - [ ] limit env to only one: throw error if it an existing env is running

PR https://github.com/liteflow-labs/liteflow-js/pull/72 thrown an error but the environment is cleanup so it breaks another instance of the command `dev`:
First instance after running `dev` in another terminal:
```
  ✔ Fetching logs
 ›   Warning: Result stream error: 14 UNAVAILABLE: GOAWAY received
  ✔ Stopping logs
  ❯ Stopping running services
    ✖ FywuwiwpqaxNMpzDW3Hh78jPzcusYPkt9X8ByHCgwTZz
      → request to http://localhost:1317/runner/exist/FywuwiwpqaxNMpzDW3Hh78jPzcusYPkt9X8ByHCgwTZz failed, reason: connect ECONNREFUSED 127.0.0.1:1317
    Deleting processes
    Stopping environment
```
```
CONTAINER ID        IMAGE                                                   COMMAND             CREATED             STATUS                        PORTS                                            NAMES
f7ce713b3fd9        mesg/engine:v0.23                                       "./engine"          2 minutes ago       Exited (137) 49 seconds ago                                                    mesg_engine
28bddd4f66cf        liteflow:FDvQhZTwYPay1CnurZ1GQowSVEhKQr6Q1p89p87T2PHS   "node index.js"     9 minutes ago       Up 48 seconds                 0.0.0.0:3005->3005/tcp                           liteflow_srv_FywuwiwpqaxNMpzDW3Hh78jPzcusYPkt9X8ByHCgwTZz
```

**Comment by NicolasMahe** [comment]
- [ ] The command `log` doesn't display any log from the service (`console.log` in the service)
this is really annoying when developing a service

**Comment by antho1404** [comment]
All this is done and the log of services is tracked here https://github.com/liteflow-labs/liteflow-js/issues/80
