### ISSUE TITLE
Add analytics in the CLI

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#71]
Add analytics and crash reports into the CLI

**Comment by antho1404** [comment]
Analytics seems complicated as firebase analytics is only web-based (and rely on `window`).
There is a similar issue here https://github.com/angular/angularfire/issues/2283

**Comment by antho1404** [comment]
This might be possible with google analytics universal and tracking of events.
Here is the firebase implementation of it https://github.com/firebase/firebase-tools/blob/master/src/track.js

**Comment by antho1404** [comment]
analytics added
