### ISSUE TITLE
Storybook Components: Offer/Form/Bid Stories have broken image url for currency

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/liteflow-js#73]
The story should display the USDC logo in the currency input and the currency select (Multicurrency story).

the Multicurrency story has a LTF token in the lift that also doesn't have a logo. Does it exist or should we use something else?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/10590599/198970662-a8026132-359c-4879-9900-ab980f496253.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/10590599/198971014-2d5a5ebe-e153-4ffa-b2f8-371765756779.png">

**Comment by antho1404** [comment]
storybook removed
