### ISSUE TITLE
Storybook Components: Sales/Auction/Button and Sales/Open/Button have some unclear stories.

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/liteflow-js#74]
Some of the stories have unclear names likes `V1`, `V2`, etc. Need to figure out if they are really useful and if they are how to properly name them.

Storybook:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/10590599/198980944-9de5c465-12f5-474a-8fcc-5614607f509a.png">

Code: 
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/10590599/198981004-6efcf7a3-b0bc-43d5-96ac-f526f7578ac9.png">

**Comment by antho1404** [comment]
storybook removed
