### ISSUE TITLE
[Bug Report] Deploying services - UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'definition' of undefined

### ISSUE THREAD

**Issue by ThomasKientz** [liteflow-labs/liteflow-js#76]
Impossible to deploy a service.

node v12.16.3

An error is logged while deploying the service "Ethereum ERC20 token" then it keeps loading in the void.

<img width="654" alt="Capture d’écran 2020-04-29 à 09 26 56" src="https://user-images.githubusercontent.com/10157845/80570945-019c3600-89fc-11ea-9c3f-d84b6b1d0035.png">

**Comment by ThomasKientz** [comment]
Oops, was indeed using node 14 and not 12

**Comment by NicolasMahe** [comment]
are you sure it's related to node 14?

**Comment by ThomasKientz** [comment]
Can not be sure, but was occurring only with node > 12
