### ISSUE TITLE
Log processes errors

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#81]
When running the `dev` command, if a process has runtime issues, these issues are not displayed in the command.

We should add the logs from the engine and filter based on the `module=orchestrator`

More information on this previous issue https://github.com/mesg-foundation/js-sdk/issues/140

**Comment by NicolasMahe** [comment]
Once PR https://github.com/mesg-foundation/engine/pull/1812 is merged, this can be implemented.

**Comment by NicolasMahe** [comment]
outdated
