### ISSUE TITLE
Cleanup not done when logs have an error

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#93]
The `onExit` function is never called when the logs returns an error because it is catch and displayed to the user (eg line 90).
Here is the output of my terminal:
```
2020-05-06T07:22:29.997Z INFO › engine › fetching logs
2020-05-06T07:22:30.042Z WARN › Result stream error: 2 UNKNOWN: Stream removed name=Error
2020-05-06T07:22:30.042Z WARN › Result stream error: 2 UNKNOWN: Stream removed name=Error
```
```
docker ps -a
CONTAINER ID        IMAGE                                                   COMMAND             CREATED             STATUS              PORTS                                              NAMES
144f6fb76ac2        liteflow:FDvQhZTwYPay1CnurZ1GQowSVEhKQr6Q1p89p87T2PHS   "node index.js"     2 minutes ago       Up 2 minutes        0.0.0.0:3005->3005/tcp                             liteflow_srv_EFJ19wcVAk13XdWb19eFCUpHeErzRiaKCTTWFy3y5r38
19ca06275a5a        liteflow:H7SvNppT4VttNxSx58becb1UfZV74htKM1czfTGvBo2b   "node index.js"     3 minutes ago       Up 2 minutes                                                           liteflow_srv_4FDwJZPL3xPfw8maXXfPnwcf7Y7FMsnhbvdb9VS1bSYC
8fe56019c029        liteflow:8KxtnsqyLsh7EgoocswHPHYEqycHNNXmPo5NJpncuHGU   "node index.js"     3 minutes ago       Up 3 minutes                                                           liteflow_srv_J6q4g36B6g6Uvjxs3rVfkqeFdNEv29dA1VLFSXQJcx6u
42a877759d61        mesg/engine:local                                       "./engine"          3 minutes ago       Up 2 minutes        0.0.0.0:1317->1317/tcp, 0.0.0.0:50052->50052/tcp   mesg_engine
```

I think the `await this.onExit(args.PATH)` should also be called when the error returns an error. Maybe you can create a promise that throw an error when the logs throw the error.

_Originally posted by @NicolasMahe in https://github.com/liteflow-labs/liteflow-js/pull/91_

**Comment by antho1404** [comment]
Way to reproduce:
- Launch an application, wait for the logs to be ready
- Kill the container of the engine

The command receives a `UNAVAILABLE: GOAWAY received` and doesn't clean up the env.

@NicolasMahe is it this kind of behavior you describes? I wasn't able to reproduce this `Stream removed` error.

Maybe we could just ignore the default "canceled" error (this one is the one we trigger) and throw an error for any other error.

**Comment by NicolasMahe** [comment]
> @NicolasMahe is it this kind of behavior you describes? I wasn't able to reproduce this `Stream removed` error.

Yes, something like this.

> Maybe we could just ignore the default "canceled" error (this one is the one we trigger) and throw an error for any other error.

We can simply throw all error and start cleanup. If the error is caused by the user (ctrl+c) then it should also cleanup the command anyway.

**Comment by NicolasMahe** [comment]
outdated issue, command dev has been deleted in https://github.com/liteflow-labs/liteflow-js/pull/260
